
#532: Runtime error 9: float invalid operation
================================================================================
Issue is closed, was reported by iArnold and has 22 comment(s).
[status.built] [status.tested] [type.bug] [Red/System]
<https://github.com/red/red/issues/532>

Testing random output of floating point numbers generated by the MT19937 algoritm function genrand-real2, generates a Runtime error 9 in Red/System.
The same code delivering the random float in a dynamic library to display generated numbers in REBOL 2 also proofs the algoritm does generate the numbers. 
The generating in the .reds file is also without problems, but activating the print statement to show them in the console causes the program to break when the second value should be printed.  



Comments:
--------------------------------------------------------------------------------

On 2013-09-14T22:20:27Z, dockimbel, commented:
<https://github.com/red/red/issues/532#issuecomment-24460384>

    A runtime error 9 is a user-level error, so if you think it is not an error in your own code, but Red's fault, you need to demonstrate it with a sample of code.
    
    An error report needs to contain a step by step description of how to reproduce the problem. Also, the shorter the code and simpler the steps, the faster it can be processed. So, try to isolate the minimum amount of code that exhibits the issue before submitting code or links to code.

--------------------------------------------------------------------------------

On 2013-09-15T19:00:29Z, iArnold, commented:
<https://github.com/red/red/issues/532#issuecomment-24477599>

    Sorry for the form I have put this up. 
    Well if it were not for the unexplainability of this issue it would not be an issue...
    
    Even odder now I am trying to reduce code and making an error and printing hardcoded value 1.0 over and over again the code fails in second iteration, where my super simple code only printing 1000 reals worked and printed the 1000 reals without complaining. 
    Only my complete testprogram suffers this crazy error.
    
    ```
        print ["--- Test 4 1000 outputs of genrand-real2 ---" lf
               "--------------------------------------------" lf]
        i: 0
        while [i < 10][ 
          print " > " 
          print [random-mt19937/genrand-real2 " "]
          if ((i % 5) = 4) [print newline ]
          i: i + 1
        ]
    ```
    
     Next form works
    
    ```
        i: 0
        while [i < 10][ 
          real-random: random-mt19937/genrand-real2
          print [real-random lf]
          i: i + 1
        ]
    ```
    
    The `if` with `i % 5 = 4`is exactly the same code as in the iteration which prints 1000 integers and this goes for the entire loop. 
    
    Perhaps this has more to do with the block I want to print and then again it is odd  the error happens the second iteration.....

--------------------------------------------------------------------------------

On 2013-09-15T19:03:41Z, iArnold, commented:
<https://github.com/red/red/issues/532#issuecomment-24477662>

    I changed a little thing and this error reoccured. 
    ONLY change:
          ;print [real-random lf]
          print [real-random ]

--------------------------------------------------------------------------------

On 2013-09-15T19:08:43Z, iArnold, commented:
<https://github.com/red/red/issues/532#issuecomment-24477768>

    ```
      print [real-random lf]
      ;print [real-random ]
      ;print real-random 
    ```
    
    Top solution works:
    
    ```
    --- Test 4 1000 outputs of genrand-real2 ---
    --------------------------------------------
    -0.23724555969238
    -0.0099935596808791
    -0.013295357115567
    0.10143111646175
    0.27933123707771
    
    -0.3013277053833
    ```
    
    (Etcetera)
    
    Both others crash the program on the _second_ (earlier inserted print statement indicate this) print 
    
    ```
    --- Test 4 1000 outputs of genrand-real2 ---
    --------------------------------------------
    -0.23724555969238
    *** Runtime Error 9: float invalid operation
    *** at: 00002034h
    logout
    ```

--------------------------------------------------------------------------------

On 2013-09-15T20:30:06Z, iArnold, commented:
<https://github.com/red/red/issues/532#issuecomment-24479492>

    random-mt19937.reds and its testprogram can be found here https://github.com/iArnold/Red/tree/master/Library/random

--------------------------------------------------------------------------------

On 2013-09-16T20:08:09Z, iArnold, commented:
<https://github.com/red/red/issues/532#issuecomment-24540254>

    So with this 'solution' in mind I hoped this line would print 5 real randoms in a row
    
    ```
    print [random-mt19937/genrand-real2 " " random-mt19937/genrand-real2 " " random-mt19937/genrand-real2 " " random-mt19937/genrand-real2 lf]
    ```
    
    But this re-introduced the error:
    
    ```
    --- Test 4 1000 outputs of genrand-real2 ---
    --------------------------------------------
    0.10143111646175 -0.013295357115567 -0.0099935596808791 -0.23724555969238
    
    *** Runtime Error 9: float invalid operation
    *** at: 00002034h
    logout
    ```
    
    Hope this now provides you enough information.

--------------------------------------------------------------------------------

On 2013-09-16T20:18:11Z, iArnold, commented:
<https://github.com/red/red/issues/532#issuecomment-24540955>

    And yes I copied random-mt19937/genrand-real2 " " only 4 times where I wanted it 5 times. My fault. 

--------------------------------------------------------------------------------

On 2013-09-17T15:05:32Z, dockimbel, commented:
<https://github.com/red/red/issues/532#issuecomment-24595419>

    You lost me with the additional posts. Please, an issue report is not a free-form chat, it's a _formal_ report of a an issue. So you need to highlight what doesn't work, **accurately** and in a **straightforward** way (no out of topic comments if possible) and what you would expect instead.
    
    Usually, the program has outputs, so show the wrong output and following it, what should be the expected output.
    
    And the most important part (unless it's totally obvious): **An error report needs to contain a step by step description of how to reproduce the problem.** (just copying from my previous reply)
    
    Here's a possible template if you never did that before:
    
    ```
    <description of the issue> (keep it as short and straightforward as possible)
    
    Result:
    <wrong output>
    
    Expected:
    <good output>
    
    <short code sample that exhibits the issue>
    or
    <step by step description of how to reproduce it>
    ```
    
    The best way would be to just replace your original post with the report I'm asking for. ;-)

--------------------------------------------------------------------------------

On 2013-09-17T17:58:58Z, iArnold, commented:
<https://github.com/red/red/issues/532#issuecomment-24609005>

    Think you lost me here.

--------------------------------------------------------------------------------

On 2013-09-17T19:45:10Z, dockimbel, commented:
<https://github.com/red/red/issues/532#issuecomment-24616354>

    I can understand your frustration, but my time is really limited and I need to spend it as efficiently as possible. With such report, it will take me a lot more time than needed to understand the issue and fix it in Red, if a fix is required. Anyway, I will have a look at your code in a few days and see how far I can get.

--------------------------------------------------------------------------------

On 2013-09-18T13:28:54Z, dockimbel, commented:
<https://github.com/red/red/issues/532#issuecomment-24663739>

    The runtime error was caused by the compiler generating an extra x87 FPU stack pop instruction after `print` when passing a function call as argument returning a float! value.
    
    This is the report I would have like to see (and that would have both saved my time and got the fix quicker for you):
    
    ---
    
    _Title_: "Runtime error 9 with no visible cause"
    
    _Description_:
    A runtime error 9 occurs in a loop on second time the `random-mt19937/genrand-real2` is called and it has no visible cause. This is the [minimum version](https://gist.github.com/dockimbel/6608971) of the code required to reproduce the problem I could come up with.
    
    It works fine when this code is turned into a shared library and loaded from Rebol2.
    
    Output when running from Red/System:
    
    ```
    -0.38120520114899
    
    *** Runtime Error 9: float invalid operation
    *** at: 00401CFDh
    ```
    
    Output when loaded as library in Rebol2:
    
    ```
    -0.38120520114899
    0.34050890803337
    -0.40837636590004
    0.14903092384338
    -0.11131640523672
    0.23243802785873
    -0.10834519565105
    0.43181106448174
    0.4575674533844
    -0.15527050197124
    ```
    
    In addition to that, the following workaround for the WHILE loop body makes the error disappear:
    
    ```
    i: 0
    real-random: 0.0
    
    while [i < 10][ 
        real-random: random-mt19937/genrand-real2
        print [real-random lf]
        i: i + 1
    ]
    ```

